name: plcmos
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - appdirs==1.4.4
  - audioread==2.1.9
  - certifi==2022.5.18.1
  - cffi==1.15.0
  - charset-normalizer==2.0.12
  - decorator==5.1.1
  - flatbuffers==2.0
  - idna==3.3
  - joblib==1.1.0
  - llvmlite==0.38.1
  - numpy==1.22.4
  - onnxruntime==1.11.1
  - packaging==21.3
  - pandas==1.4.2
  - pycparser==2.21
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - pytz==2022.1
  - requests==2.27.1
  - scipy==1.8.1
  - six==1.16.0
  - threadpoolctl==3.1.0
  - tqdm==4.64.0
  - urllib3==1.26.9
  - pip:
    - librosa==0.9.1
    - SoundFile
